site_url : https://asalvadorc.github.io/modelos_BD
site_name: BD - Modelado de Bases de Datos
copyright: >
  © 2026 Alicia Salvador —
  <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">
  Licencia CC BY-NC-SA 4.0
  </a>

exclude_docs: |
  Model_E-R/soluciones.md
  Model_Relacional/soluciones.md
  Normalizacion/soluciones.md

theme:
  name: material
  font:
    text: Inter
    code: JetBrains Mono
  logo: assets/logo.png
  favicon: img/favicon.png
  features:
  - toc.follow
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.instant
  - navigation.instant.progress
  - navigation.sections
  - navigation.expand
  - navigation.indexes
  - navigation.tracking
  - navigation.footer

  - search.suggest
  - search.highlight
  - search.share

  - content.code.copy
  - content.tabs.link
  - content.tooltips
  - content.action.edit
  - content.action.view

  - header.autohide

  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro

extra_css:
  - css/extra.css

extra_javascript:
  - javascripts/lightbox.js

markdown_extensions:
  - admonition
  - tables    
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true     
  - md_in_html
  - pymdownx.details
  - meta
  - toc:
      toc_depth: 2
   



nav:
  - 🏠 Inicio:
    - index.md
    - RA y CE: RA_CE.md
    - Introducción: introduccion.md
    - Cómo utilizar la IA para aprender: IA.md
  #- 📅 Hoja de Ruta Semipresencial: guia_estudio.md
  - T1. Modelo Entidad-Relación:
    - Model_E-R/index.md
    - 1. Introducción: Model_E-R/1_introduccion.md
    - 2. Ejemplo:Empresa: Model_E-R/2_ejemplo.md
    - 3. Entidades y Atributos: Model_E-R/3_las_entidades_del_modelo_er.md
    - Ejercicio: Model_E-R/ejercicios.md
    - 4. Las Relaciones: Model_E-R/4_las_relaciones_del_modelo_er.md
    - Práctica guiada: Model_E-R/9_practica0.md
    - Ejercicios: Model_E-R/ejercicios0.md
    - 5. Relaciones ternarias: Model_E-R/5_relaciones_de_grado_mayor_que_dos.md
    - 6. Modelo E/R Extendido: Model_E-R/6_modelo_er_extendido.md
    - 7. Restricciones externas: Model_E-R/7_restricciones_externas.md
    - 8. Resumen elementos gráficos: Model_E-R/8_resumen_elementos_graficos.md
    - Ejercicios: Model_E-R/ejercicios1.md
    - Soluciones: proximamente.md
  - T2. Modelo Relacional:
    - proximamente.md
    #- Model_Relacional/index.md
    #- 1. Introducción: Model_Relacional/1_introduccion.md
    #- 2. Estructura del Modelo Relacional: Model_Relacional/2_estructura_del_modelo_relacional.md
    #- 3. Transformación del M. E/R al M. Relacional: Model_Relacional/3_transformacion_del_m_er_al_m_relacional.md
    #- 4. Restricciones: Model_Relacional/4_restricciones.md
    #- 5. Resumen: Model_Relacional/resumen.md
    #- Ejercicios: Model_Relacional/5_ejercicios.md
    #- Soluciones: proximamente.md
  - T3. Normalización:
    - proximamente.md
    #- 1. Introducción: Normalizacion/1_introduccion.md
    #- 2. Primera Forma Normal (1FN): Normalizacion/2_primera_forma_normal_1fn.md
    #- 3. Dependencia Funcional: Normalizacion/3_dependencia_funcional.md
    #- 4. Segunda Forma Normal (2FN): Normalizacion/4_segunda_forma_normal_2fn.md
    #- 5. Dependencia Funcional Transitiva: Normalizacion/5_dependencia_funcional_transitiva.md
    #- 6. Tercera Forma Normal (3FN): Normalizacion/6_tercera_forma_normal_3fn.md
    #- 7. Forma Normal Boyce-Codd (FNBC): Normalizacion/7_forma_normal_boycecodd_fnbc.md
    #- Ejemplo Completo: Normalizacion/Ejemplo_completo.md
    #- Resumen: Normalizacion/resumen.md
    #- Ejercicios: Normalizacion/ejercicios.md
    #- Soluciones: proximamente.md